from enum import Enum
from BaseEnums import *
#параметры ячеек
#в САНТИМЕТРАХ
class CellsParameters( Enum ):
    
    WIDTH_BETWEEN_CELLS_CENTIMETER = 3.2
    WIDTH_OF_CELL_CENTIMETER = 1.7
    HEIGHT_OF_CELL_CENTIMETER = 1
    WIDTH_FROM_QR_CODE_TO_CELL_CENTIMETER = 2.7

    WIDTH_FROM_QR_CODE_TO_CELL_INCH = WIDTH_FROM_QR_CODE_TO_CELL_CENTIMETER / INCH 
    WIDTH_BETWEEN_CELLS_INCH = WIDTH_BETWEEN_CELLS_CENTIMETER / INCH 
    WIDTH_OF_CELL_INCH = WIDTH_OF_CELL_CENTIMETER / INCH 
    HEIGHT_OF_CELL_INCH = HEIGHT_OF_CELL_CENTIMETER / INCH  
