from BaseEnums import *

WIDHT_OF_BIG_QR_CODE_CENTIMETER = 2.3
HEIGHT_OF_BIG_QR_CODE_CENTIMETER = 2.3

WIDHT_OF_BIG_QR_CODE_INCH = WIDHT_OF_BIG_QR_CODE_CENTIMETER / INCH 
HEIGHT_OF_BIG_QR_CODE_INCH = HEIGHT_OF_BIG_QR_CODE_CENTIMETER / INCH 



