INCH = 2.54
#индексы 
X = 0
Y = 1
WIDTH = 2
HEIGHT = 3

#МИЛЛИМЕТРЫ!!!!!
#МЕТКИ
WIDTH_OF_MARK = 9
HEIGHT_OF_MARK = 9

WIDTH_FORM = 210
HEIGHT_FORM = 297

#Большой код!!!
#берем побольше заранее
DISTANCE_TO_BIG_QR_CODE_RIGHT_SIDE = 27
DISTANCE_TO_BIG_QR_CODE_TOP_SIDE = 27
WIDTH_OF_BIG_QR_CODE = 33
HEIGHT_OF_BIG_QR_CODE = 33
X_DESTINATION_FROM_BIG_QR_CODE_TO_MARK = 15
Y_DESTINATION_FROM_BIG_QR_CODE_TO_MARK = 13

#маленькие коды
WIDTH_OF_SMALL_QR_CODE = 17
HEIGHT_OF_SMALL_QR_CODE = 17
START_POS_FOR_SMALL_QR_CODE_SEARCH = 30


RESERVE_PIXELS_VALUE = 5

#РАССТОЯНИЯ
DISTANCE_FROM_CODE_TO_CELL = 33
DISTANCE_BETWEEN_CELLS = 32

#РАССТОЯНИЯ ОТ БОЛЬШОГО КОДА
DISTANCE_TO_FORM_LEFT_SIDE = 154
DISTANCE_TO_FORM_RIGHT_SIDE = 24
DISTANCE_TO_FORM_TOP_SIDE = 25
DISTANCE_TO_FORM_BOTTOM_SIDE = 239

#расстояние от маленького кода снизу до ячейки
DISTANCE_TO_CELL_FROM_BOTTOM_SIDE_OF_CODE = 3
#расстояние от маленького кода сверху до ячейки
DISTANCE_TO_CELL_FROM_TOP_SIDE_OF_CODE = 2

#ЯЧЕЙКИ
HEIGHT_OF_CELL = 10
WIDTH_OF_CELL = 15

WIDTH_OF_BOX = 1


#DEBUG
DEBUG_FORM_DETECTOR = 0
#search status (qr code detector)

FULL_QR_SEARCH = 0 #полный поиск по всему листу
Y_QR_SEARCH = 1 #поиск только по Y
X_QR_SEARCH = 2 #поиск только по X


#threshold_reason (qrcodescan)
QR_CODE_DETECTOR_THRESHOLD_REASON = 0
FORM_DETECTOR_THRESHOLD_REASON = 1
TRESHOLD_ON_MARKED_STATUS = 0.15


PIL_IMAGE = 0
FILE_NAME = 1
IMAGE_WORKER = 2

UNDEFINED_DPI_VALUE = -1

YES_EXIF = 1
NO_EXIF = 0

