INCH = 2.54

#индексы 
X = 0
Y = 1
WIDTH = 2
HEIGHT = 3

#МИЛЛИМЕТРЫ!!!!!
#МЕТКИ
WIDTH_OF_MARK = 9
HEIGHT_OF_MARK = 9

WIDTH_FORM = 210
HEIGHT_FORM = 297

#Большой код
DISTANCE_TO_BIG_QR_CODE_RIGHT_SIDE = 27
DISTANCE_TO_BIG_QR_CODE_TOP_SIDE = 27
WIDHT_OF_BIG_QR_CODE = 36
HEIGHT_OF_BIG_QR_CODE = 36
X_DESTINATION_FROM_BIG_QR_CODE_TO_MARK = 15
Y_DESTINATION_FROM_BIG_QR_CODE_TO_MARK = 13

#маленькие коды
WIDTH_OF_SMALL_QR_CODE = 17
HEIGHT_OF_SMALL_QR_CODE = 17
START_POS_FOR_SMALL_QR_CODE_SEARCH = 30

#РАССТОЯНИЯ
DISTANCE_FROM_CODE_TO_CELL = 32
DISTANCE_BETWEEN_CELLS = 37

#ЯЧЕЙКИ
HEIGHT_OF_CELL = 10
WIDHT_OF_CELL = 15

#search status (qr code detector)

FULL_QR_SEARCH = 0 #полный поиск по всему листу
Y_QR_SEARCH = 1 #поиск только по Y
X_QR_SEARCH = 2 #поиск только по X


#threshold_reason (qrcodescan)
QR_CODE_DETECTOR_THRESHOLD_REASON = 0
FORM_DETECTOR_THRESHOLD_REASON = 1
TRESHOLD_ON_MARKED_STATUS = 0.15


PIL_IMAGE = 0
FILE_NAME = 1
IMAGE_WORKER = 2

UNDEFINED_DPI_VALUE = -1

YES_EXIF = 1
NO_EXIF = 0

